//A global used to hold the const string used with amplify publish and subscribe

var HandleEvents = {
        ON_SIGN_IN : "ON_SIGN_IN",
        ON_SIGN_OUT : "ON_SIGN_OUT",
        HANDLE_LOOKUP_REQUESTED : "HANDLE_LOOKUP_REQUESTED",
        HANDLE_CREATED_SUCCESS : "HANDLE_CREATED_SUCCESS",
        HANDLE_CREATED_LOCAL_SUCCESS : "HANDLE_CREATED_LOCAL_SUCCESS",
        HANDLE_DELETED_SUCCESS : "HANDLE_DELETED_SUCCESS",
        HANDLE_DELETED_ERROR : "HANDLE_DELETED_ERROR",
        HANDLE_SAVED_SUCCESS : "HANDLE_SAVED_SUCCESS",
        HANDLE_SAVED_ERROR : "HANDLE_SAVED_ERROR", 
        HANDLE_MODEL_CHANGED : "HANDLE_MODEL_CHANGED",
        SELECTED_PREFIX_CHANGED : "SELECTED_PREFIX_CHANGED",
        PREFIX_CREATED : "PREFIX_CREATED",
        SPECIFIC_SITE_SELECTION_CHANGED : "SPECIFIC_SITE_SELECTION_CHANGED"
};